# Generated by Django 4.1.5 on 2023-07-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
