# Generated by Django 4.1.5 on 2023-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=64)),
                ('roll', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
