# Generated by Django 4.1.5 on 2023-06-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('Movie_Name', models.CharField(max_length=65)),
                ('Hero_Name', models.CharField(max_length=65)),
                ('Heroine_Name', models.CharField(max_length=65)),
                ('Rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
    ]
