# Generated by Django 4.1.5 on 2023-06-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie_model',
            table=None,
        ),
    ]
