# Generated by Django 4.1.5 on 2023-06-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_movie_model_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Model',
            new_name='Movies_Model',
        ),
        migrations.AlterModelTable(
            name='movies_model',
            table=None,
        ),
    ]
