# Generated by Django 4.1.5 on 2023-06-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_movie_model_movies_model_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies_model',
            table='Movies',
        ),
    ]
