# Generated by Django 4.1.5 on 2023-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Name', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
