# Generated by Django 4.1.5 on 2023-07-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='to_do_model',
            table='todo_table',
        ),
    ]
