# Generated by Django 4.1.5 on 2023-09-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo')),
                ('roll', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'sutdent',
            },
            bases=('testapp.contactinfo',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo')),
                ('subject', models.CharField(max_length=64)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=('testapp.contactinfo',),
        ),
    ]
