# Generated by Django 4.1.5 on 2023-09-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feild_one', models.CharField(max_length=64)),
                ('feild_two', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Second',
            fields=[
                ('feild_three', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('feild_fourth', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent_second_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='testapp.parent_second')),
                ('parent_one_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.parent_one')),
                ('feild_five', models.CharField(max_length=64)),
                ('feild_six', models.CharField(max_length=64)),
            ],
            bases=('testapp.parent_one', 'testapp.parent_second'),
        ),
    ]
