# Generated by Django 4.1.5 on 2023-07-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
