# Generated by Django 4.1.5 on 2023-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mob',
            field=models.IntegerField(),
        ),
    ]
