# Generated by Django 4.1.5 on 2023-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('movie_name', models.CharField(max_length=64)),
                ('hero_name', models.CharField(max_length=64)),
                ('heroine_name', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
