# Generated by Django 4.1.5 on 2023-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_No', models.IntegerField()),
                ('Employee_Name', models.CharField(max_length=64)),
                ('Employee_Salary', models.FloatField()),
                ('Employee_Address', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
